### PR TITLE
Ignore projectile-globally-ignored-suffixes in projectile-grep.

### LINKED ISSUE #727: Files in projectile-globally-ignored-file-suffixes not ignored by projectile-grep
I have many build files ignored by projectile by using `projectile-globally-ignored-file-suffixes`. Many of these are minified JavaScript files: `.min.js`. When using `projectile-grep` these files are grepped and produce false positives in the grep buffer. Further, because these files have all text on one line, it can slow Emacs down to a crawl.

I think it would be great if `projectile-grep` ignored files using `project-ignored-file-suffixes`.

### PR DESCRIPTION
**Pull request by jdufresne**
Fixes #727

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm guessing this is also an issue with `ag` as well.

**Comment by jdufresne** [comment]
@bbatsov I added the same support for `ag`. I'm not very familiar with this tool nor do I ever use it. I have tested the `grep` version thought. So please let me know if the `ag` change looks sane. Thanks!

**Comment by bbatsov** [comment]
I guess this should work. :-)

**Comment by bbatsov** [comment]
I've merged this manually.

**Pull request closed without merging**
