### PR TITLE
projectile-files-via-ext-command: avoid touching users' windows

### LINKED ISSUE #1625: projectile-find-file creates additional windows on Win10
`projectile-git-submodule-command`, with default value `"git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'"`, uses `tr` which isn't necessarily available on windows.  The missing `tr` utility causes an error which leaves an additional window open.  Setting `projectile-git-submodule-command` to `nil` resolves the problem for those of us that don't care about submodules.

`Projectile 20201214.839`

### PR DESCRIPTION
**Pull request by maurelio1234**
hopefully fixes #1625 and #1624 

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/CONTRIBUTING.md)
- [x] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing ([`eldev test`](https://github.com/doublep/eldev))
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [x] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [x] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
Did you figure out which command exactly results in the extra buffer?

**Comment by maurelio1234** [comment]
I tried to write a TU like that:

```elisp
          (it "does not create new windows"
              (let ((count-windows-before (count-windows))
                    (count-windows-after))
                (projectile-files-via-ext-command "" "nonExistentCommand")
                (setq count-windows-after (count-windows))
                (expect count-windows-after :to-equal count-windows-before)))
```

But it passes even without my fix... I'm not sure how we could test that.

**Comment by maurelio1234** [comment]
> Did you figure out which command exactly results in the extra buffer?

shell-comand does that (around line 3720):

```elisp
	    (when (and error-file (file-exists-p error-file))
              (when (< 0 (file-attribute-size (file-attributes error-file)))
                (with-current-buffer (get-buffer-create error-buffer)
                  (let ((pos-from-end (- (point-max) (point))))
                    (or (bobp)
                        (insert "\f\n"))
                    ;; Do no formatting while reading error file,
                    ;; because that can run a shell command, and we
                    ;; don't want that to cause an infinite recursion.
                    (format-insert-file error-file nil)
                    ;; Put point after the inserted errors.
                    (goto-char (- (point-max) pos-from-end)))
                  (display-buffer (current-buffer))))```

It seems we cannot disable this 'feature'.

**Comment by bbatsov** [comment]
We can always inline and tweak the built-in function. Not sure which approach is better.

**Comment by maurelio1234** [comment]
> We can always inline and tweak the built-in function. Not sure which approach is better.

I guessed `save-window-excursion` was ok, because there's already anyther one (line 1276, commit: 184d3451c9258cfbbfa2b26a07c7daeee2e9a605)

**Comment by bbatsov** [comment]
I think the suggestion solution is fine. My only concern was that the code is not particularly straightforward right now. Thanks for tackling this so quickly!

**Pull request merged**
