### PR TITLE
Add known autoconf and cscope files to projectile-project-root-files

### PR DESCRIPTION
**Pull request by vsedach**

### CODE REVIEW

**Comment by bbatsov** [comment]
I think you'd normally have those in a make project, so adding them seems redundant to me.

**Comment by mattiasb** [comment]
Autotools-projects generally doesn't have a toplevel `Makefile` but the project instead has one or several `Makefile.am` and then a `configure.ac` at the top.

**Comment by vsedach** [comment]
Correct, you won't get a Makefile until you run configure.

**Comment by bbatsov** [comment]
Roger that! Thanks for this improvement!

**Pull request merged**
