### PR TITLE
Add minimal support for shadow-cljs

### PR DESCRIPTION
**Pull request by Macroz**
Add minimal support for [http://shadow-cljs.org/](shadow-cljs) projects.

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [x] You've updated the changelog (if adding/changing user-visible functionality)
- [x] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by Macroz** [comment]
@bbatsov Would you be willing to consider this addition? I don't use `shadow-cljs` much yet but I noticed this was missing.

I think most `shadow-cljs` projects have Git or some other type of projectile supported project type already. However it's nice to get the plain project working as well.

**Comment by bbatsov** [comment]
Don't shadow projects typically have build tool marker in them? (e.g. `deps.edn`, `project.clj`, etc) You can't do much with shadow without adding some deps.

**Comment by Macroz** [comment]
As for dependencies, you can do fine without as described in the [manual](https://shadow-cljs.github.io/docs/UsersGuide.html#_build_tool_integration). But it's true, like I note in the original question, that most projects will have e.g. Git. But isn't that true for the other types as well? As it is now, projectile + CIDER does not work in a plain shadow-cljs project unless you add the `.projectile` file or Git. This would fix that.

**Comment by bbatsov** [comment]
Usually the other project types bring to the table some build commands, which is why we have them. They are not added just for their value as project markers. Anyways, there's no harm in adding this, but it won't add much value either.

**Comment by Macroz** [comment]
I guess this is not worthwhile so I'll close the issue.

**Pull request closed without merging**
