### PR TITLE
Add check for dirty projects

### PR DESCRIPTION
**Pull request by muahah**
Add two functions to check if Git projects are dirty
(uncommitted changes and/or unpushed commits).
Use [vc-check-status](https://github.com/thisirs/vc-check-status) package.

`projectile-check-project-dirty` check if the project associated with the given directory is dirty.
`projectile-see-dirty-projects` list all dirty projects (very useful before leaving Emacs after a day of hard work)

I used it for a while now and it work flawlessly for me.
If the community is interested, I can work on it a little more 
(add tests, maybe support for others vcs... ).

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [x] You've updated the changelog (if adding/changing user-visible functionality)
- [x] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
Seems like a useful addition, but it should definitely support multiple VCS. I avoid adding features that are specific just for a certain VC (even if it's as popular as git).

**Comment by bbatsov** [comment]
I'm also a bit concerned about having to depend on another package just for this one command. I prefer to limit the number of dependencies.

**Comment by muahah** [comment]
I will check if its possible to rely on `vc` built-in functions instead of `vc-check-status`.
It should solve both issues.

**Comment by bbatsov** [comment]
Any progress here?

**Comment by muahah** [comment]
Unfortunately no,
I keep it in mind but don't have time to work on it right now.

**Comment by muahah** [comment]
In fact I took a look to the available functions of `vc`, 
it seems pretty straightforward to implement this functionality with `vc-dir`.
I should be able to come with something soon.

**Comment by bbatsov** [comment]
Excellent!

**Comment by muahah** [comment]
It needs some cleaning, but it's working for git.
It should also work with any VCS supported by `vc`, but I only use git so I was not able to test that.

**Comment by muahah** [comment]
I cleaned up a little.
Some remarks concerning this version :
- It seems to be slower than the previous version specific to git.
- It's doesn't check for unpulled/unpushed commits (`vc` doesn't seem to check that...).
- It should work with every VCS supported by `vc`, but I only tested it with git.

Any suggestions of improvement ?

**Comment by muahah** [comment]
Note : 
the first use of this function can be (really) slow,
It's mainly because `vc-dir` check for every file of the repository.
I don't see any (easy) way of making this faster.
Maybe checking the repository status asynchroneously could be a solution if it become a real problem.

**Comment by muahah** [comment]
I made the proposed modifications.
`projectile-browse-dirty-project` should now appear in the menu and in the manual.
Also added `C-c p V` as key-binding for `projectile-browse-dirty-projects` ('V' for version control).
And made the list of checked states customizable (`projectile-vcs-dirty-states`).

**Comment by bbatsov** [comment]
👍

**Pull request merged**
