### PR TITLE
convert defadvices to new style advice

### PR DESCRIPTION
**Pull request by spwhitton**
Convert projectile's use of `defadvice` to `nadvice.el`, that is, `defun` plus `advice-add`.

Thanks for projectile!

### CODE REVIEW

**Comment by syohex** [comment]
nadvice was introduced at Emacs 24.4. Does projectile supports Emacs 24.4 or higher version?

**Comment by spwhitton** [comment]
It looks like the Travis build failed because Travis is using a version of Emacs older than 24.4.

Emacs 24.4 is in Debian Stable.  That means it's not exactly bleeding-edge.  So perhaps we could expect anyone using an older version who wanted to use projectile to download an older tag.  But that's up to the project maintainer.

**Comment by bbatsov** [comment]
Frankly, I never thought about the minimum supported version. In my mind it was 24.1 (although it's probably not). If Debian stable really ships 24.4, then I guess setting it as the minimum supported version is OK. What's the Emacs version in RHEL 7?

**Comment by spwhitton** [comment]
[This page](https://git.centos.org/summary/?r=rpms/emacs) suggests 24.3.

**Comment by bbatsov** [comment]
Guess we can't convert the advices just yet then.

**Pull request closed without merging**
