### PR TITLE
[Fix #1019] Generalizing test/implementation lookups

### LINKED ISSUE #1019: Is there a way to jump to a test named the same way but in a different directory?
I've been looking through the code but it seems like the only way to influence the test file checker only considers the file base name. I'm currently in the situation where the project I'm working on arranges tests like this:
- src/some-file.js
- test/some-file.js

Is there any way to teach projectile about this?

### PR DESCRIPTION
**Pull request by jordonbiondo**
This PR puts the existing suffix and prefix based test/implementation lookup feature behind another layer of abstraction. The purpose of this is to allow users greater control over how projectile handles it's knowledge of test files and their relationship to implementation files.

While this PR creates the possibility for more extensive customization it does not include any, and oes not change the current behavior of projectile in any way. It simply allows others, or potentially other packages, to use projectile for projects that don't fit into the prefix/suffix naming convention assumed by projectile. Refer to #1019 for an example of why this is needed. It would be my goal after acceptance of this PR to create a new PR or new package that uses this new customization layer to support `ember-cli` projects in projectile.

This is a work in progress, there are currently no tests, or example implementations. I have opened this PR now to begin the discussion about whether or not this feature can/would be accepted into projectile, or if a different solution to the same problem would be desired.

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`make test`)
- [x] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by bbatsov** [comment]
I'm fine with the proposed changes.

**Comment by bbatsov** [comment]
@jordonbiondo Any progress here?

**Comment by bbatsov** [comment]
@jordonbiondo ping :-)

**Comment by Qquanwei** [comment]
@jordonbiondo Have any progress ? Orz

**Comment by jordonbiondo** [comment]
Sorry all, I stopped working on the project that prompted me to do this so I lost track of it, I'll try to rebase this up on the latest code and see if I can take it from there.

**Comment by dakra** [comment]
@jordonbiondo another ping ;)

**Comment by jordonbiondo** [comment]
Yeah to be realistic, I'm never going to pick this back up

**Pull request closed without merging**
