### PR TITLE
Fix bug in compilation-find-file-projectile-find-compilation-buffer

### PR DESCRIPTION
**Pull request by Silex**
@bbatsov oops :sweat_smile: 

Thanks to @mookid for noticing!

### CODE REVIEW

**Comment by Silex** [comment]
@mookid: I had to move from e924ecf to ea3eb81 because of the `formats` variable, because otherwise it'd do `(compilation-find-file marker filename directory '(nil))`.

Do you see a better way to write this?

**Comment by mookid** [comment]
+ note that instead of (car (remove-if-not ...   you can use find-if.
+ otherwise, nothing to say about your code. it's a bit ugly because the function has a bunch of arguments, but as long as you tested it that's ok.  Maybe you can try to catch the current bug in a unit test?

**Comment by kaushalmodi** [comment]
@bbatsov Please merge this ASAP.

**Comment by Silex** [comment]
@bbatsov: just a thought, maybe consider giving rights to merge to the repository for trusted people of your choice for situations like this? Then people would have a list of contributors to summon in case of urgencies (I can volunteer).

**Comment by Silex** [comment]
:+1:

**Pull request merged**
