### PR TITLE
fixed helm-projectile-ag not properly ignoring files in .projectile f…

### PR DESCRIPTION
**Pull request by mijoharas**
…older

This is basically the same change as in #708 I think I just neglected to put it in both places there.

### CODE REVIEW

**Comment by bbatsov** [comment]
Please, capitalise the commit message and use present simple tense in it.

**Comment by mijoharas** [comment]
Done. Will keep that in mind for future commits to projectile.

**Comment by bbatsov** [comment]
:-) Now I have to ask you to use an imperative form. Basically, these are the rules we follow http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by mijoharas** [comment]
third time lucky. :smile:

**Comment by bbatsov** [comment]
:+1: Thanks!

**Pull request merged**
