### PR TITLE
Don't check for TRAMP connection state in projectile-project-root {WIP}

### LINKED ISSUE #1328: Switching to a remote project does not work (again)
This is some resurgence of #1252 that was fixed a few months ago, but shows up again in the latest Projectile version (although with a different error message).

## Expected behavior

Switching to a remote project (for example `/ssh:someserver:/path/to/project`) with C-c p-p should bring to that project.

## Actual behavior

An error message "projectile-switch-project-by-name:  Directory /ssh:someserver:/path/to/project is not a project" is displayed.

## Steps to reproduce the problem

1 - Add the remote project the list of known project, for example "/ssh:someserver:/path/to/project"
2 - Switch to that project with C-c p-p

### Projectile version information

```
Projectile 20181017.710
```

### Emacs version

*26.1*

### Operating system

*macos 10.14*

### LINKED ISSUE #1340: Project is removed from the list if the project root is not found
## Expected behavior

Projects should be kept in the project list, even if the project root is not found. For example, a project with a remote root directory may not be reachable if the host or the network connection is down.

This is related to #1328.

## Actual behavior

Projects with no project root are removed from the project list.

## Steps to reproduce the problem

- Create a `~/testproject` directory
- Add the `~/testproject` to the project list with <kbd>M-x projectile-add-known-project</kbd>
- Delete the `~/testproject` directory
- Switch to the project.

### Projectile version information

```
Projectile 20181024.1707
```

### Emacs version

*26.1*

### Operating system

*macOS 10.14*

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Bind TRAMP variable non-essential to non-nil instead if the user
should not be disturbed (by password prompt/hanging connections).

Fixes #1340
Fixes #1328

**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting a PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [ ] All tests are passing (`make test`)
- [ ] The new code is not generating bytecode or `M-x checkdoc` warnings
- [ ] You've updated the changelog (if adding/changing user-visible functionality)
- [ ] You've updated the readme (if adding/changing user-visible functionality)

Thanks!

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
Maybe more projectile functions need to bind `non-essential` to `t` to prevent hanging/interacting (password prompts). I just added it to `projectile-find-file-in-known-projects`.

@smaret Would you mind to test this branch? 🎃

**Comment by smaret** [comment]
Thanks a lot @juergenhoetzel !

I've tested the branch and it does fix #1328 🎉 but not #1340.

**Comment by bbatsov** [comment]
> Maybe more projectile functions need to bind non-essential to t to prevent hanging/interacting (password prompts). I just added it to projectile-find-file-in-known-projects.

That's not something I'm particularly excited about. :-) This tramp support has been nothing, but a pain in the butt for me and I don't even use tramp. I don't want to litter a ton of commands with dynamic bindings for tramp to behave.

**Comment by bbatsov** [comment]
To be clear - I'd like to provide good support for TRAMP users, but I don't want this to happen at the expense of adding a lot of complexity to the codebase.

**Pull request closed without merging**
