### PR TITLE
[Fix #695] Improve find detection portability

### LINKED ISSUE #695: If ignored directory doesn't have proper permissions, projectile-find-file displays "find: 'foldername': permission denied"
Project structure : 
-----------------------
.projectile
-- folder_1 [doesn't have permission to access directory]
-- folder_2
    --- test1.c
    --- test2.c
    --- test3.c

.projectile:
-------------
-/folder_1

launch emacs and invoke projectile-find-file
screenshot from 2015-03-28 19 36 47

### PR DESCRIPTION
**Pull request by dibenede**
Distinguish between nul and /dev/null depending on Windows usage.
Avoid generating output buffers and spurious *Messages* entries.
Defer generic command detection until required to avoid startup time hit.

### CODE REVIEW

**Comment by dibenede** [comment]
The "nul" usage on Windows is untested. Otherwise, seems to work on OS X, CentOS 5.10, and Ubuntu 14.04. Windows was tested via elisp evaluation in *scratch* and yielded the expected find command string with cygwin installed.

**Comment by bbatsov** [comment]
Seems to me this spinning out of control. As someone mentioned already - perhaps `find . \\! -perm +444 -prune -o \\( -type f -print0` will work everywhere? Seems generic enough to me.

**Comment by dibenede** [comment]
I completely agree. The GNU man page suggested there were some differences between -readable and the -perm usage (i.e. readable is a superset). If you're ok with the differences, I'm more than happy to give you the trivial default.

**Comment by bbatsov** [comment]
Simpler would be better. We wasted too much time on this already I think.

**Pull request closed without merging**
