### PR TITLE
[Fix #794] Update helm-projectile-file-actions for latest helm version

### LINKED ISSUE #794: helm-projectile-hack-actions: (wrong-type-argument listp helm-find-files-actions)
After today's helm upgrade from melpa I got the error as in title.
Perhaps helm-projectile must be fixed to adapt new helm changes

https://github.com/emacs-helm/helm/issues/1088

### PR DESCRIPTION
**Pull request by zachlatta**
- Fixes #794 
- Fixes emacs-helm/helm#1088
- Fixes syl20bnr/spacemacs#2282

Took @thierryvolpiatto's suggested patch from emacs-helm/helm#1088, updated it per @bsuh's suggestion, and then turned it into a PR. All ready for merge :shipit:.

### CODE REVIEW

**Comment by bsuh** [comment]
Change

```
   (cdr (helm-attr 'action (or helm-source-find-files
                               (helm-make-source "Find files" 'helm-source-ffiles))
                   'ignorefn))
```

to

```
   (helm-attr 'action (or helm-source-find-files
                          (helm-make-source "Find files" 'helm-source-ffiles))
                   'ignorefn)
```

**Comment by sewkokot** [comment]
Confirm, removing 'cdr' fixes the issue. Thanks!

**Comment by zachlatta** [comment]
Will do my best to make that fix tonight so we can get this merged!

**Comment by zachlatta** [comment]
Alright! Updated and ready (I think!) for merge.

**Comment by zeusdeux** [comment]
This needs to be merged asap please :)

**Comment by microamp** [comment]
Yes, that would be awesome once verified. Been byte compiling the file with the change above, and it's been working fine for me.

**Comment by bbatsov** [comment]
Closing in favour of https://github.com/bbatsov/projectile/pull/796

**Pull request closed without merging**
