### PR TITLE
Add tramp/network/latency benchmarking suite (WIP)

### PR DESCRIPTION
**Pull request by thomasf**
## What?

This is a benchmark system made up of a fig/docker combination.

## Motivation

Many projectile changes affects slow file systems like TRAMP.
We need something to do benchmark regression tests and a way for different people to run the same test to make reasoning about performance issues a lot easier.

## How it works

I have built this prototype using a fig/docker combination, everything is runnable through the Makefile.

It should start by first running `make fig-up` followed by `make fig-test`.

A forced full rebuild/run cycle can be triggered using fig: `fig build --no-cache && fig up`.

## The docker containers

There are four images and three running instances:

**Projectile-testdata**

This is a base image for all other images that needs the test data files. It's does not run by its own.

The content is currently a few shallow git checkouts, an emacs source release expanded and some empty directories.

**Projectile**

The tests are run from this instance, it is basically emacs + cask + the projectile repository + tools like scm and what else might be required for tests. It inherits from the projectile-testdata image.

**sshd**

Runs a sshd daemon that the projectile instance connects to. It inherits from the projectile-testdata image.

**polipo**

A caching http proxy to support quicker cask rebuilds from scratch.

### Top priority (Must be done before merge)

* Emit benchmark results as csv or similar and add some diagram creation script.
* Verify that the results are reliable for finding performance issues. (I think it's good, wait for diagrams to verify further)
* Evaluate if ert really is the right tool for running this suite. It might not be needed. 

### Medium priority (Should be done before merge)

* Add even more tests, try to cover the major areas of whats most often called.
* Sober everything up to contribution standards.
  
### Low priority (can be done after merge)

* Make it possible to run suite outside docker.
* Add complex high level tests that simulates a user working on code. Test cleanup might be a nut to sovle.
* Add sensible functions that does seletive instrumentation when results needs to be looked at in more detail.

### CODE REVIEW

**Comment by Silex** [comment]
@thomasf: I fixed parts of your Dockerfile at https://github.com/Silex/projectile/commits/performance, feel free to cherry-pick these commits once you rebased on top of `master`.

**Comment by thomasf** [comment]
@Silex great! Feature wise all of this feels solid now.. This is next up for non work related open source for me, to clean this up so that it is suitable for a merge

**Comment by Silex** [comment]
@thomasf: projectile's internal API has become quite a mess. For example, I discovered `projectile-buffer-ignored-p` is not really used where it should be, e.g `projectile-mode` will be enabled in almost buffers and the `:lighter` part of it will call `projectile-project-name` even for theorically ignored buffers.

So I wanted to fix it, but I'm like... should I fix it in `projectile-project-name`? should I fix it in `projectile-mode`? Do we want projectile-mode to be enabled for ignored buffers?

I think we are at a point where a lot needs some refactoring, here's a (incomplete) list that I have in mind:

- Cache
  - Decide what kind of cache we want (directories <> project roots? project <> project files?)
  - Decide if we really want automatic cache expiration (probably yes?)
  - Write/use a generic caching library so all future caching uses the same mechanism.
- Refactor `projectile-project-root`
  - Decide how the find-project-root functions can be tweaked by the user
  - Rewrite them so they're easier to cache
  - Decide where the caching happens
- Refactor `projectile-*-ignore`
  - Decide if projectile-mode should be enabled for ignored buffers
  - Decide what of projectile-mode should be enabled if we decide to enable it
  - Decide where ignoring happens (in the fundamental functions?)

I think it'd be nice to write some specifications about how projectile is supposed to work.

@bbatsov: please share your thoughts on this

**Comment by thomasf** [comment]
Yeah, the internals should really make use of defined data structures instead of randomly invoking the same thing over and over again.
The complexity of the internal API was a big trigger for writing the performance suite in the first place.

**Comment by Silex** [comment]
@thomasf: maybe we can start writing some wiki of the ideal projectile data structures? improve it over time and when it's ready, start hacking?

**Comment by thomasf** [comment]
My thoughts are currently to start by by creating a basic cl-defstruct representing a project to have something to play with.

**Comment by Silex** [comment]
@thomasf: good idea, maybe we should use `eieio` isntead? there's an example at https://github.com/milkypostman/melpa/issues/2394

**Comment by thomasf** [comment]
Even though I dont really have the time right now I want to rebase and see how performance has changed over the last few month :)

**Comment by Silex** [comment]
Good idea. Don't forget my little patches while you rebase ;)

**Comment by thomasf** [comment]
@silex your changes are in my branch now and I quickly made just enough to have it all running again not accounting for possible changes in projectile that changes the results..

Here are new plots along with the ones from last year:

[2014-12-04-06_57_46projectile-bench.el.plot1](http://framtiden.medeltiden.org/~a00001/2014-12-04-06_57_46projectile-bench.el.plot1.svg)
[2015-04-07-23_20_37projectile-bench.el.plot1](http://framtiden.medeltiden.org/~a00001/2015-04-07-23_20_37projectile-bench.el.plot1.svg)

[2014-12-04-06_57_46projectile-bench.el.plot2](http://framtiden.medeltiden.org/~a00001/2014-12-04-06_57_46projectile-bench.el.plot2.svg)
[2015-04-07-23_20_37projectile-bench.el.plot2](http://framtiden.medeltiden.org/~a00001/2015-04-07-23_20_37projectile-bench.el.plot2.svg)

[2014-12-04-06_57_46projectile-user-simulation-1-bench.el.plot1](http://framtiden.medeltiden.org/~a00001/2014-12-04-06_57_46projectile-user-simulation-1-bench.el.plot1.svg)
[2015-04-07-23_20_37projectile-user-simulation-1-bench.el.plot1](http://framtiden.medeltiden.org/~a00001/2015-04-07-23_20_37projectile-user-simulation-1-bench.el.plot1.svg)

[2014-12-04-06_57_46projectile-user-simulation-1-bench.el.plot2](http://framtiden.medeltiden.org/~a00001/2014-12-04-06_57_46projectile-user-simulation-1-bench.el.plot2.svg)
[2015-04-07-23_20_37projectile-user-simulation-1-bench.el.plot2](http://framtiden.medeltiden.org/~a00001/2015-04-07-23_20_37projectile-user-simulation-1-bench.el.plot2.svg)

I don't have time to evaluate it all but the distributions between cache/no cache seems generally better now.

**Comment by Silex** [comment]
@thomasf: nice, fyi the "Quick & sloppy" commit contains a typo (jsut)

It's a shame we're all swamped and have no time to work on projectile. One of the problem is that "what needs to be done" looks like a huge task. Maybe the first task would be to make a list of small achievable tasks to do?

**Comment by bbatsov** [comment]
Closing due to lack of activity.

**Comment by thomasf** [comment]
I works fine though..

**Pull request closed without merging**
