### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by platonbjs**
----------------------------------------------VERSION GITHUB-------------------------------------------------
Hola!
Somos un grupo de estudiantes de la Universidad Complutense de Madrid (UCM) y estamos
haciendo una campaña de concienciación sobre el uso de licencias.

Razones por las que usar una licencia:

- Es FáCIL de usar: escoge la licencia, copia el texto genérico y listo! Ya puedes usarla en tus proyectos. En el siguiente [link](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) puedes encontrar más información:
- LIMíTAS que usos pueden tener las personas para usar tu contenido, de esta manera evitas problemas de copias y plagios 
- Compartir es poder! Las licencias libres te dan credito en todo momento permitiendo que otros usen tu trabajo bajo TUS condiciones.
En el siguiente [video](https://www.youtube.com/watch?v=OnmWFxlG2GA) se explican los tipos de licencias para que puedas escoger una que se adapte a tus necesidades

Hemos elegido la licencia GPLv3 para este pull request.
Gracias por tu atención! Esperamos que te haya servido de ayuda

------------------------------------------------------------------------------------------------------------------
Hello!
We are a group of students of Universidad Complutense de Madrid (UCM) and we are working on an awareness campaign about types and uses of licences.

There are many reasons to use licences in your code:

- It's EASY to use: choose the licence, copy the generic text and ready! Now you can use it in your projects You can found more information in the following [link](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository ) 

- You LIMIT the uses of your code, in this way you will avoid possible legal problems about copies and plagiarism
- Share is power! The freeware licences give to you credit all the time. Allow third people use it with YOUR conditions

The following [youtube link](https://www.youtube.com/watch?v=OnmWFxlG2GA) show the existing types of licences to choose one which adapt better to your needs

We have chosen GPL v3 license for this pull request.

Thank you a lot for your attention! We hope you the contents has been helpful

### CODE REVIEW

**Comment by bbatsov** [comment]
Thanks for the PR! Why `.md`? I see this file has no markup in it.

**Comment by platonbjs** [comment]
> Thanks for the PR! Why `.md`? I see this file has no markup in it.

Hi. Some developer prefer LICENSE.md instead of LICENSE for consistency purpose (CONTRIBUTING.md, README.md) but if you prefer I can change it. Do you prefer LICENSE or LICENSE.txt?

**Comment by bbatsov** [comment]
Simply LICENSE is fine. That's how it's typically distributed.

**Comment by platonbjs** [comment]
Renamed. Thank you for your support

**Pull request merged**
