### PR TITLE
Autoload for projectile-locate-dominating-file

### PR DESCRIPTION
**Pull request by rgrinberg**
Trivial change to allow using `projectile-locate-dominating-file` with autoload

### CODE REVIEW

**Comment by bbatsov** [comment]
Why would you want to autoload functions which are not commands? That's extremely uncommon.

**Comment by rgrinberg** [comment]
In doom-emacs these functions are used as library functions. On second
thought, I’m not sure why we don’t just require projectile

**Comment by hlissner** [comment]
I agree that library functions shouldn't be autoloaded by packages, so I've fixed this on Doom's end. This can be closed.

**Comment by bbatsov** [comment]
Thanks!

**Pull request closed without merging**
