### PR TITLE
Add a command to run shell in project's root directory

### PR DESCRIPTION
**Pull request by danskarda**
When working with multiple projects, I find it useful to have different shells for each project. This patch adds a command to launch shell in current root directory.

The shell buffer will be called `*shell project-name*`.

### CODE REVIEW

**Comment by bbatsov** [comment]
That's a good idea. I'd add 2 more similar commands - one that starts `term` and one that starts `eshell` (probably using a common keyboard prefix). You should also mention this in the changelog.

**Comment by danskarda** [comment]
Add term / eshell. There are two options:

1.  add customization using dispatch var, where user makes choice between three alternatives
2.  add keyboard prefix (`C-c p x t`, `C-c p x e` and `C-c p x s`)

I am conservative user and 100% time stick to one shell, so I would prefer 1. What do you think?

Add changelog : good catch, thanks.

Once you think about solution for var vs dispatch key, I will prepare the commit and squash everything to original patch for final review.

**Comment by bbatsov** [comment]
I'm leaning towards option two, as I'm not sure what would be the name of a generic command governed by a defcustom in this case.

**Comment by bbatsov** [comment]
Or maybe we can have just one command invoking a shell or an eshell (with a prefix arg).

**Comment by bbatsov** [comment]
P.S. This will solve #943.

**Comment by bbatsov** [comment]
ping :-)

**Comment by danskarda** [comment]
pong:-)

Implemented. Rebased. Squashed.

**Pull request merged**
