### PR TITLE
Show correct project name when switching projects

### PR DESCRIPTION
**Pull request by raxod502**
See discussion on #1067.

### CODE REVIEW

**Comment by raxod502** [comment]
Note, this still doesn't fix the issue where the same project name is shown in the mode line as is shown in the minibuffer, but it does at least make it so the right project name is shown in the minibuffer without messing up the project name in the mode line when you switch back to the previous buffer.

**Comment by bbatsov** [comment]
Add some comment in the source why we're doing this, otherwise someone is bound to guess.

**Comment by raxod502** [comment]
Agreed, and done.

**Comment by bbatsov** [comment]
👍

**Pull request merged**
