### PR TITLE
Add find-other-file support for indirect buffer

### PR DESCRIPTION
**Pull request by qqldd**
This change add `projectile-find-other-file` for indirect buffer that is created by `C-x 4 c`

### CODE REVIEW

**Comment by bbatsov** [comment]
Hmm, isn't the file name the same for the original and the indirect buffers?

**Comment by qqldd** [comment]
@bbatsov Yes, it is the same. However, `buffer-file-name` cannot get the file name for indirect buffer. For example, the original buffer named A, we cloned a new buffer named AC. When using `buffer-file-name` on AC, it returns `nil`. Only the original buffer has the associated file name.

**Comment by bbatsov** [comment]
So, I'm guessing this is a problem in other places of the codebase as well. Probably we should create a simple helper function that works on indirect buffers?

**Comment by bbatsov** [comment]
Ping :-)

**Comment by qqldd** [comment]
Just saw this pending request. I didn't use indirect buffer for a while. I will try to see if I can make an update to this.

**Comment by bbatsov** [comment]
I'm closing this PR due to no recent activity. Feel free to re-open it if you ever come back to it.

**Pull request closed without merging**
