### PR TITLE
Correct python project types used in the test prefix search.

### PR DESCRIPTION
**Pull request by proofit404**
Projectile can't toggle between implementation and test correctly for python projects. This pull request update test prefix search predicates.

### CODE REVIEW

**Comment by proofit404** [comment]
I apologize for the molestation, but `BUMP`.

**Comment by bbatsov** [comment]
Drop the dots from the commit messages.

**Comment by proofit404** [comment]
Done.

**Comment by proofit404** [comment]
Thanks!

**Pull request merged**
