### PR TITLE
General test functions improvements + add midje support

### PR DESCRIPTION
**Pull request by arichiardi**
According to issue #757 I have implemented support for [Midje](https://github.com/marick/Midje) here.
I apologize but I am not a proper elisp expert...I am ready for the bashing :smile:

### CODE REVIEW

**Comment by expez** [comment]
@bbatsov is going to ask you to reference the issue this is solving, squash the commits into one and likely limit the length of your commit messages to a 50 char summary.

Otherwise this looks good to me!

**Comment by arichiardi** [comment]
Oh ok, I kept it separated because they are two different things: one adds the ```midje``` support, the other changes some ```projectile``` behaviour...aka I sneaked in something that I thought it was an improvement...I was even thinking of appending here yesterday's work on test generation, but maybe is too much :smile:

**Comment by bbatsov** [comment]
What's this `.midje.clj`? I've never head of it. Is it some marker you made up yourself?

**Comment by arichiardi** [comment]
Ahaha no :smile:, not myself, it is ```midje```'s actual configuration file, which unfortunately has to be used as marker as I had no other way to distinguish between normal and ```midje``` tests...of course if there is a better way I am all ears...
It is optional and might go in ```$HOME``` as well as in project's root.

**Comment by bbatsov** [comment]
Why not simply set the project type in `.dir-locals`. This might be useful for all project types that can't be easily auto-detected.

**Comment by arichiardi** [comment]
Yep is a good idea, I just did not have enough knowledge about ```projectile``` for implementing this :smile: It could either be identified ```.midje.clj``` or ```.dir-locals```... can you please point me to where this is done for other ```project-type```s as well? I will add it.

**Comment by bbatsov** [comment]
We should have a `projectile-project-type` buffer local variable, which is checked in the `projectile-project-type` function. If it's set we use it to determine the type of the project, otherwise we try to autodetect it. This variable should be set `.dir-locals.el` in the root of the respective project.

**Comment by arichiardi** [comment]
Oh wow great, in that case I don't think I need to add anything else. I will test it though to see if it's working fine here.

**Comment by bbatsov** [comment]
> Oh wow great, in that case I don't think I need to add anything else. I will test it though to see if it's working fine here.

We don't really have this behaviour. I suggested it might be a good idea to have it, because of all project types we can't auto-detect. Adding this would be trivial.

**Comment by arichiardi** [comment]
Ok agree, will work on that. I'd better change the PR title and I wanted also to ask you if it would be ok to add #642 as well here or have a separate PR for that.

**Comment by arichiardi** [comment]
So, would ```projectile-project-type``` be a list? At the moment the test prefix/suffix is a unique string and I guess that if the project can be of multiple types, also the test generating functions will need to change accordingly..

**Comment by marcinant** [comment]
@arichiardi  It's just my suggestion. Eclipse supports project `natures` and this is pretty good idea.
A lot of projects can be detected as multiple types for example: wordpress-theme with bower and composer support.

Projectile doesn't provide specialized tools for these projects however this variable could be used by some external tools to run commands on detected project types.

**Comment by arichiardi** [comment]
Yes, I am familiar with Eclipse's natures, and we could take some ideas from it. There are buildspec too inside a ```.project``` file. We should put all this inside our ```.dir-locals.el``` I guess.

See this excerpt:
```xml
		<buildCommand>
			<name>org.eclipse.pde.SchemaBuilder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.pde.PluginNature</nature>
		<nature>org.eclipse.jdt.core.javanature</nature>
		<nature>ccw.nature</nature>
	</natures>
</projectDescription>
```

**Comment by bbatsov** [comment]
Let's make changes one step at a time - for now having the ability to set the project type manually would be more than enough.

**Comment by marcinant** [comment]
Personally I gave up on projectile again ;) 101 issues unresolved, 21 unmerged PR.
I don't have time to wait for changes in `projectile` core and would like to GTD and move forward.

So, what I do with project type detection. For example something like this:
This function detects composer project type and is a part of PR which is still awaiting.
```
 (defun composer-project-type ()
   "Function to determine project type from composer.json."
    (when (projectile-verify-file "composer.json")
      (let ((composer-json (json-read-file (projectile-expand-root "composer.json"))))
         (cdr (assoc 'type composer-json)))))
```
Then with `clock-in-prepare-hook` I would like to detect project type and do something when I start to work on TODO (for example: I can start/stop apache server on clock-in/clock-out)
```
 (defun idemacs/clock-in-prepare-hook ()
      (let* ((project-type (if (composer-project-type)
                               (composer-project-type)
                             (projectile-project-type)))
```
So, I got additional variable `project-type` which is a kind of wrapper for `projectile-project-type`.
I don't need to use `.dir-locals.el`. Project type is defined in `composer.json` and is properly detected. If not, then fallback to projectile.

This sucks, this is ugly workaround, but as long as `projectile` development is so slow then I see no better solution. `.dir-locals.el` are ok. However I don't like to maintain any additional config file unless I have to.

**Comment by arichiardi** [comment]
It is a nice way to get the project-type...using a customizable lamdba instead of a just var. This will require executing code from .dir-locals.el ... But hey, if you control the project why not?

**Comment by bbatsov** [comment]
> Personally I gave up on projectile again ;) 101 issues unresolved, 21 unmerged PR.
> I don't have time to wait for changes in projectile core and would like to GTD and move forward.

Most of the open issues are features suggestions and small bugs. I'm an extremely busy person and this is an open-source project. If you don't like something you can always fix it.

> This sucks, this is ugly workaround, but as long as projectile development is so slow then I see no better solution. .dir-locals.el are ok. However I don't like to maintain any additional config file unless I have to.

I wish I had more time to appease everyone, but I don't. People can either complain or contribute. I'm fine  either way.

**Comment by marcinant** [comment]
@bbatsov  Don't take this personal. I just described things how they are.
Issues not resolved, PR not accepted. 

I perfectly understand this is Open Source and non-profit.

So, I had choice: wait... , fork and maintain branch with my patches accepted by myself, keep using `vanilla` branch of `projectile` and use workarounds and extensions.
And this is what I did.

**Comment by bbatsov** [comment]
> PR not accepted.

I don't accept PRs which I feel are incomplete. I should be crazy to start merging everything that was ever proposed. Check the outstanding PRs and you'll see that most of them have at least a few comments from me.

**Comment by arichiardi** [comment]
@bbatsov ```projectile-project-type``` is already the function we use to check the project using its files.

To summarize:
1. A ```.dir-local.el``` var (in the future can be a list of "natures") called ```projectile-custom-project-type``` will be the first way to define a project, it would great to have a list of supported project symbols somewhere for the user.
2. The normal ```projectile-verify-files``` is the second way that at the moment checks if all files in the specified list are matching.

Tell me please if everything sounds right :smile: .

**Comment by bbatsov** [comment]
In elisp you can have a variable and a function with the same name. They
live in separate namespaces.

On Wednesday, June 3, 2015, Andrea Richiardi <notifications@github.com>
wrote:

> @bbatsov <https://github.com/bbatsov> projectile-project-type is already
> the function we use to check the project using its files.
>
> To summarize:
> 1. A .dir-local.el var (in the future can be a list of "natures") called
> projectile-custom-project-type will be the first way to define a project,
> it would great to have a list of supported project symbols somewhere for
> the user.
> 2. The normal projectile-verify-files is the second way that at the
> moment checks if all files in the specified list are matching.
>
> Tell me please if everything sounds right [image: :smile:] .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/projectile/pull/758#issuecomment-108451139>.
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by arichiardi** [comment]
Oh that story about lisp-1 vs lisp-2 right :+1:

**Comment by arichiardi** [comment]
Of course always ready to change in case of elisp mistakes or bugs :+1:

**Comment by marcinant** [comment]
> I don't accept PRs which I feel are incomplete. I should be crazy to start merging everything that was ever proposed. Check the outstanding PRs and you'll see that most of them have at least a few comments from me.

It's your opinion. My is different. My PR contain code to detect some project types and it does it's job.
I need it so I had options as I described above.

**Comment by arichiardi** [comment]
Mmm I might have made a mistake, why is ```symbol is void: projectile-test-prefix-function```  ? Should it be define to ```projectile-test-prefix``` by default?

**Comment by arichiardi** [comment]
Ok found, will squash when is fine :wink:

**Comment by arichiardi** [comment]
This last commit adds [#642](https://github.com/bbatsov/projectile/issues/642).

It does not save the buffer because from what I have seen it looks like it is not the way ```projectile-find-implementation-or-test-other-window``` and ```projectile-toggle-between-implementation-and-test``` work but it creates the necessary folders if it cannot find them so that the user can just save when needed.

Of course it would be great to save automagically but I didn't do it as maybe this is something we need to discuss (and I can leave with it). An option could be to set the buffer modified.

@expez @bbatsov

**Comment by bbatsov** [comment]
This PR should have been 3 PRs - one for midje, one for the project-type and one for the test creation.

**Comment by arichiardi** [comment]
Yes I agree, do you want me to split? Or we can just keep three separate commits...

**Comment by bbatsov** [comment]
Both options are fine. You'll also have to rebase your branch on top of the current `master`.

**Comment by arichiardi** [comment]
What about my question above, would it be ok to add a set buffer modified when we create a test buffer?

**Comment by bbatsov** [comment]
> Of course it would be great to save automagically but I didn't do it as maybe this is something we need to discuss (and I can leave with it). An option could be to set the buffer modified.

It's OK not to save it.

**Comment by arichiardi** [comment]
and will it read it from ```.dir-local.el``` ? Clever! :smile: Will change

**Comment by arichiardi** [comment]
The advantage of my previous approach is that if you change ```.dir-local.el```, that ```alist``` gets loaded again.. allowing runtime changes..```defvar-local``` does not seems to behave like that here on my machine...but I guess it is not a big issue...

**Comment by arichiardi** [comment]
I have also fixed a bug that when the project was ```lein-test``` instead of ```lein-midje``` (suffix instead of prefix)

**Comment by arichiardi** [comment]
Gerat! I forgot to modify the README and Changelog...

**Comment by bbatsov** [comment]
I saw. I'll update them myself.

**Comment by arichiardi** [comment]
Ok thank you very much b :smile:

**Comment by expez** [comment]
Great work @arichiardi!

**Comment by arichiardi** [comment]
:balloon: :beers: :tada: :balloon: :tada: :beers: :cake:

:sunglasses: 

:bow: 

Ok, enough with my emotions :smile:
Thanks for your (and Bozhidar) hints and corrections...

**Comment by caioaao** [comment]
From my understanding, midje doesn't enforce a naming for test files. All it does is loading tests from the project's `:test-paths` (see [this wiki page](https://github.com/marick/Midje/wiki/Lein-midje-basics)). Is it possible to add this kind of flexibility to projectile? Is there an API for adding test-finding functions to projectile? That may be a better design rather than hard-coding every test-finding strategy here. With this design, one could write a package that inserts the desired functionality to projectile.

**Comment by arichiardi** [comment]
I think projectile is hard coding just common patterns but still gives the flexibility to add your own stuff. See above for `.dir-locals.el` customizations.., it sounds like a reasonable approach. More sophisticated solutions were taken into consideration (like Eclipse's natures) but probably someone needs to step in and take charge of that.

**Comment by caioaao** [comment]
This is not what I meant. I know there is a way of providing a custom `projectile-project-type`, but I wanted to know if there is a way of providing specific functions to find test files. For instance, providing a function that uses CIDER to get the file namespace and tries to find the correct test file based on that.

**Pull request merged**
